cmake: clang: remove -Wno-gnu
Removing `-Wno-gnu` from Clang compiler flags exposes GNU extension
warnings. One such warning is `-Wgnu-folding-constant`, which is
triggered in `tests/kernel/common/src/pow2.c` because `Z_POW2_CEIL`
relies on built-ins in array sizes.

Fix this by locally suppressing the warning in the test.

Compilation failure without fix:
/home/jules/zephyrproject/zephyr/tests/kernel/common/src/pow2.c:29:6: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
   29 | char static_array1[Z_POW2_CEIL(1)];
      |      ^

Tests ran:
`kernel.common.toolchain` on `native_sim` with `llvm`.